apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vq3lin2yu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vq3lin2yu-go 
  name: vq3lin2yu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vq3lin2yu-go 
